### PR TITLE
fix: duplicate message filter

### PR DESCRIPTION
**Pull request by debendraoli**
Checks for duplicate message before relaying message.

This handles two cases, when message has failed and relayer is unware and abilty to run multiple relayer at once.

### CODE REVIEW

**Review by viveksharmapoudel — COMMENTED** [review]
messageReceived check in processMessages and cleared if necessary, here the process is just repeated, so is it necessary ?

**Comment by debendraoli** [comment]
> messageReceived check in processMessages and cleared if necessary, here the process is just repeated, so is it necessary ? 

Yes, that's the case we need to check whether the message is processing otherwise if we try to send that same message which is already processing we might get a duplicate message error on contract.

Reference: https://tracker.lisbon.icon.community/contract/cxb2b31a5252bfcc9be29441c626b8b918d578a58b

**Comment by viveksharmapoudel** [comment]
> > messageReceived check in processMessages and cleared if necessary, here the process is just repeated, so is it necessary ?
> 
> Yes, that's the case we need to check whether the message is processing otherwise if we try to send that same message which is already processing we might get a duplicate message error on contract.
> 
> Reference: https://tracker.lisbon.icon.community/contract/cxb2b31a5252bfcc9be29441c626b8b918d578a58b

In this case adding same check again...will it prevent transaction failure? if it could prevent the failure, then the estimate step should have failed due to this reason and attempting it next time processMessage should clear the message....

**Comment by debendraoli** [comment]
Not relevant

**Pull request closed without merging**
